/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package merklehellman;

import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Design extends javax.swing.JFrame {
    
    static int [] cifradoTxt; 
    /**
     * Creates new form Design
     */
    public Design() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_textoC = new javax.swing.JTextField();
        btn_cifrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_clavePublica = new javax.swing.JLabel();
        txt_binarioTexto = new javax.swing.JLabel();
        txt_cifrado = new javax.swing.JLabel();
        tf_descifrar = new javax.swing.JTextField();
        btn_descifrar = new javax.swing.JButton();
        txt_textobinarioD = new javax.swing.JLabel();
        txt_descifrado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_modulos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mochila_Martin López Robles");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Merkle y Hellman");

        btn_cifrar.setText("Cifrar");
        btn_cifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("S'  = { 3, 5, 12, 21}");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("m  = 45");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("w  = 32");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("w' = 38");

        txt_clavePublica.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_clavePublica.setText("Clave Publica ");

        txt_binarioTexto.setText("Binario: ");

        txt_cifrado.setText("Cifrado:");

        tf_descifrar.setEditable(false);

        btn_descifrar.setText("Descifrar");
        btn_descifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarActionPerformed(evt);
            }
        });

        txt_textobinarioD.setText("Binario:");

        txt_descifrado.setText("Descifrado:");

        jLabel6.setText("Modulos:");

        txt_modulos.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txt_clavePublica))
                            .addComponent(txt_binarioTexto)
                            .addComponent(txt_cifrado)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_descifrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(tf_textoC, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_descifrar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_cifrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(1, 1, 1))))
                            .addComponent(txt_textobinarioD)
                            .addComponent(txt_descifrado)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_modulos))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel1)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txt_clavePublica))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_cifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_textoC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_binarioTexto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_cifrado)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_descifrar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(tf_descifrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_modulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_textobinarioD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descifrado)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarActionPerformed
        // TODO add your handling code here:
        String texto = tf_textoC.getText().trim();
        
        if(!texto.isEmpty() && soloLetrasNumeros(texto)){
            String binario = Merkle.convetirTextoBin(texto);
        String [] bits = Merkle.dividirBits(binario);
        StringBuilder bits_binario = new StringBuilder("Binario: ");
        StringBuilder cifrado = new StringBuilder("Cifrado: ");
        StringBuilder cifrado_text = new StringBuilder();
        
        for(String b:bits){
            bits_binario.append(b+" ");
        }
        txt_binarioTexto.setText(bits_binario.toString());  
        
        cifradoTxt = Merkle.cifrado(clave_publica, binario);
        for(int c: cifradoTxt){
            cifrado.append(c+" ");
            cifrado_text.append(c +" ");
        }
        txt_cifrado.setText(cifrado.toString());
        tf_descifrar.setText(cifrado_text.toString());
        
        }else{
            JOptionPane.showMessageDialog(rootPane, "Al parecer el cmapo de texto esta vacío o incluye caracteres no validos.");
        }
        
        
        
        
    }//GEN-LAST:event_btn_cifrarActionPerformed

    private void btn_descifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarActionPerformed
        // TODO add your handling code here:
         String texto = tf_descifrar.getText().trim();
         String descifrado_bin = Merkle.descifrado(cifradoTxt, mochila, m, w_in, txt_modulos);
         txt_textobinarioD.setText("Binario: "+descifrado_bin);
         txt_descifrado.setText("Descifrado: "+Merkle.convetirTextoDec(descifrado_bin));
        
    }//GEN-LAST:event_btn_descifrarActionPerformed

    /**
     * @param args the command line arguments
     */
    
        static int [] mochila = {3, 5, 12 ,21}; //S -> mochila
        static int m    = 45; //valor mayor a la suma de la mochila
        static int w    = 32; //valor mayor a la suma ae la mochila y menor a m
        static int w_in = 38; //solo factor comun en 1
        static int [] clave_publica = new int[4];
    
    
    public static void main(String args[]) {
        
     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
                ClavePublica();
            }
        });
    }

    
    public static void ClavePublica(){
         //Calculo de la llave publica
        int sub_indices = 0;
        int contador = 0;
        StringBuilder clave = new StringBuilder();
        clave.append("Clave pública = {");
        for (int s:mochila) {
            sub_indices = (w * s % m) % m;              //Formula
            clave_publica [contador] = sub_indices;     //Se llena la clave publica
            contador = contador+1;                      //Contador aux para llenar la llave
            //System.out.print(sub_indices +"  ");   
            clave.append(" ").append(sub_indices).append(",");
        }   
        clave.append("}");
        txt_clavePublica.setText(clave.toString());
    }
    
    
     //Método soloLetras, verifica que solo contenga letras
    public static boolean soloLetrasNumeros(String cadena){
        for (int x = 0; x < cadena.trim().length(); x++) {
            char c = cadena.charAt(x);
            // Si no está entre a y z, ni entre A y Z, ni es un espacio
            if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == ' ' || c >= '0' || c >= '9')) {
                return false;}}
        return true;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cifrar;
    private javax.swing.JButton btn_descifrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_descifrar;
    private javax.swing.JTextField tf_textoC;
    private javax.swing.JLabel txt_binarioTexto;
    private javax.swing.JLabel txt_cifrado;
    public static javax.swing.JLabel txt_clavePublica;
    private javax.swing.JLabel txt_descifrado;
    private javax.swing.JLabel txt_modulos;
    private javax.swing.JLabel txt_textobinarioD;
    // End of variables declaration//GEN-END:variables
}
