/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sustitucion;

import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Design extends javax.swing.JFrame {

    /**
     * Creates new form Design
     */
    public Design() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jToggleButton1 = new javax.swing.JToggleButton();
        Paneles = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_cifrarCesar = new javax.swing.JTextPane();
        NEncriptar = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btn_cifrarCesar = new javax.swing.JButton();
        btn_limpiarCesarE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        NDesencriptar = new javax.swing.JComboBox<>();
        btn_descifrarCesar = new javax.swing.JButton();
        btn_limpiarCesarD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta_descrifrarCesar = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ta_descifrarPolybios = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        ta_cifrarPolybios = new javax.swing.JTextArea();
        btn_cifrarPolybios = new javax.swing.JButton();
        btn_descifrarPolybios = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btn_limpiarDesPoly = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ta_cifrarTrithemius = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_descrifrarTritemius = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        CBKeyCifrar = new javax.swing.JComboBox<>();
        btn_cifrarTri = new javax.swing.JButton();
        btn_limpiarCifrarTri = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CBKeydescifrar = new javax.swing.JComboBox<>();
        btn_descifrarTri = new javax.swing.JButton();
        btn_limpiarDesTri = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Botones = new javax.swing.JPanel();
        btn_Cesar = new javax.swing.JButton();
        btn_Polybios = new javax.swing.JButton();
        btn_Trithemius = new javax.swing.JButton();
        btn_Info = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Métodos de sustitiución");

        Paneles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Paneles.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        Paneles.setEnabled(false);
        Paneles.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setName("Cesar"); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("C E S A R");

        jScrollPane1.setViewportView(ta_cifrarCesar);

        NEncriptar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("N");

        btn_cifrarCesar.setText("Cifrar");
        btn_cifrarCesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarCesarActionPerformed(evt);
            }
        });

        btn_limpiarCesarE.setText("Limpiar");
        btn_limpiarCesarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCesarEActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("N");

        NDesencriptar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btn_descifrarCesar.setText("Descifrar");
        btn_descifrarCesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarCesarActionPerformed(evt);
            }
        });

        btn_limpiarCesarD.setText("Limpiar");
        btn_limpiarCesarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCesarDActionPerformed(evt);
            }
        });

        jLabel7.setText("Texto a Cifrar");

        jLabel9.setText("Texto a Descifrar");

        ta_descrifrarCesar.setColumns(20);
        ta_descrifrarCesar.setRows(5);
        jScrollPane2.setViewportView(ta_descrifrarCesar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_cifrarCesar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_limpiarCesarE))
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(NDesencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_descifrarCesar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_limpiarCesarD))
                            .addComponent(jLabel9)
                            .addComponent(jScrollPane2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel5)))
                .addGap(115, 115, 115))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel7))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NEncriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cifrarCesar)
                            .addComponent(btn_limpiarCesarE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(NDesencriptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_descifrarCesar)
                        .addComponent(btn_limpiarCesarD)))
                .addGap(65, 65, 65))
        );

        Paneles.addTab("CESAR", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("P O L Y B I O S");

        ta_descifrarPolybios.setColumns(20);
        ta_descifrarPolybios.setRows(5);
        jScrollPane3.setViewportView(ta_descifrarPolybios);

        ta_cifrarPolybios.setColumns(20);
        ta_cifrarPolybios.setRows(5);
        jScrollPane4.setViewportView(ta_cifrarPolybios);

        btn_cifrarPolybios.setText("Cifrar");
        btn_cifrarPolybios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarPolybiosActionPerformed(evt);
            }
        });

        btn_descifrarPolybios.setText("Descifrar");
        btn_descifrarPolybios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarPolybiosActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        btn_limpiarDesPoly.setText("Limpiar");
        btn_limpiarDesPoly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarDesPolyActionPerformed(evt);
            }
        });

        jLabel2.setText("Texto a cifrar: ");

        jLabel3.setText("Texto a descifrar:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_cifrarPolybios)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btn_descifrarPolybios)
                                .addGap(18, 18, 18)
                                .addComponent(btn_limpiarDesPoly))
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_cifrarPolybios)
                        .addComponent(jButton3))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_descifrarPolybios)
                        .addComponent(btn_limpiarDesPoly)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        Paneles.addTab("POLYBIOS", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("T R I T H E M I U S");

        ta_cifrarTrithemius.setColumns(20);
        ta_cifrarTrithemius.setRows(5);
        jScrollPane5.setViewportView(ta_cifrarTrithemius);

        ta_descrifrarTritemius.setColumns(20);
        ta_descrifrarTritemius.setRows(5);
        jScrollPane6.setViewportView(ta_descrifrarTritemius);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Key");

        CBKeyCifrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btn_cifrarTri.setText("Cifrar");
        btn_cifrarTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarTriActionPerformed(evt);
            }
        });

        btn_limpiarCifrarTri.setText("Limpiar");
        btn_limpiarCifrarTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCifrarTriActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Key");

        CBKeydescifrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        btn_descifrarTri.setText("Descifrar");
        btn_descifrarTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarTriActionPerformed(evt);
            }
        });

        btn_limpiarDesTri.setText("Limpiar");
        btn_limpiarDesTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarDesTriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBKeyCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cifrarTri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiarCifrarTri, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBKeydescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_descifrarTri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_limpiarDesTri)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(229, 229, 229))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jScrollPane5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(CBKeyCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cifrarTri)
                    .addComponent(btn_limpiarCifrarTri)
                    .addComponent(jLabel11)
                    .addComponent(CBKeydescifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_descifrarTri)
                    .addComponent(btn_limpiarDesTri))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        Paneles.addTab("TRITHEMIUS", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Programas de Sustitución");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Creados por Martin López Robles");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("IC-0703");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cifrado.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(203, 203, 203))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(258, 258, 258)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(191, 191, 191))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(265, 265, 265))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel12)
                .addGap(38, 38, 38)
                .addComponent(jLabel15)
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(33, 33, 33))
        );

        Paneles.addTab("INFO.", jPanel5);

        Botones.setBackground(new java.awt.Color(255, 255, 255));

        btn_Cesar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/corona-de-laurel.png"))); // NOI18N
        btn_Cesar.setBorder(null);
        btn_Cesar.setBorderPainted(false);
        btn_Cesar.setContentAreaFilled(false);
        btn_Cesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CesarActionPerformed(evt);
            }
        });

        btn_Polybios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/matriz.png"))); // NOI18N
        btn_Polybios.setBorderPainted(false);
        btn_Polybios.setContentAreaFilled(false);
        btn_Polybios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PolybiosActionPerformed(evt);
            }
        });

        btn_Trithemius.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/triangulo-en-circulo.png"))); // NOI18N
        btn_Trithemius.setBorderPainted(false);
        btn_Trithemius.setContentAreaFilled(false);
        btn_Trithemius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrithemiusActionPerformed(evt);
            }
        });

        btn_Info.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/informacion.png"))); // NOI18N
        btn_Info.setBorderPainted(false);
        btn_Info.setContentAreaFilled(false);
        btn_Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BotonesLayout = new javax.swing.GroupLayout(Botones);
        Botones.setLayout(BotonesLayout);
        BotonesLayout.setHorizontalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_Cesar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btn_Polybios, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Trithemius, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97)
                .addComponent(btn_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );
        BotonesLayout.setVerticalGroup(
            BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Cesar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Polybios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Trithemius, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Botones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Botones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setBounds(0, 0, 616, 447);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CesarActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(0);
    }//GEN-LAST:event_btn_CesarActionPerformed

    private void btn_PolybiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PolybiosActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(1);
    }//GEN-LAST:event_btn_PolybiosActionPerformed

    private void btn_TrithemiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrithemiusActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(2);
    }//GEN-LAST:event_btn_TrithemiusActionPerformed

    private void btn_InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InfoActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(3);
    }//GEN-LAST:event_btn_InfoActionPerformed

    private void btn_cifrarCesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarCesarActionPerformed
        // Cifrado Cesar
        String texto = ta_cifrarCesar.getText().trim();
        if(!texto.isEmpty()){
         String text_cifrado = Cesar.cifradoCesar(texto, NEncriptar.getSelectedIndex()+1);
         ta_descrifrarCesar.setText(text_cifrado);
        }else{
            JOptionPane.showMessageDialog(null, "Al parecer el campo de texto esta vacío","Error" , JOptionPane.WARNING_MESSAGE);
        }
               
    }//GEN-LAST:event_btn_cifrarCesarActionPerformed

    private void btn_descifrarCesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarCesarActionPerformed
        // TODO add your handling code here:
        String texto = ta_descrifrarCesar.getText().trim();
        if(!texto.isEmpty()){
        Cesar.descifradoCesar(texto, NDesencriptar.getSelectedIndex()+1);
        }else{
            JOptionPane.showMessageDialog(null, "Al parecer el campo de texto esta vacío","Error" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_descifrarCesarActionPerformed

    private void btn_limpiarCesarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCesarEActionPerformed
        // TODO add your handling code here:
        ta_cifrarCesar.setText(" ");
    }//GEN-LAST:event_btn_limpiarCesarEActionPerformed

    private void btn_limpiarCesarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCesarDActionPerformed
        // TODO add your handling code here:
        ta_descrifrarCesar.setText(" ");
    }//GEN-LAST:event_btn_limpiarCesarDActionPerformed

    private void btn_cifrarPolybiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarPolybiosActionPerformed
        // TODO add your handling code here:
        String texto = ta_cifrarPolybios.getText().trim();
        if(soloLetras(texto) && !texto.isEmpty()){
            String text_cifrado = Polybios.Encriptar(texto);
            ta_descifrarPolybios.setText(text_cifrado);
        }else{
            JOptionPane.showMessageDialog(null, "Al parecer el campo de texto contine caracteres no validos o esta vacio." +
                        "\n Revise su texto y evite los saltos de linea.","Error" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_cifrarPolybiosActionPerformed

    private void btn_descifrarPolybiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarPolybiosActionPerformed
        // TODO add your handling code here:
        String texto = ta_descifrarPolybios.getText().trim();
        if(soloLetras(texto) && !texto.isEmpty()){
             Polybios.Desencriptar(texto);  
        }else{
            JOptionPane.showMessageDialog(null, "Al parecer el campo de texto contine caracteres no validos o esta vacio." +
                        "\n Revise su texto y evite los saltos de linea.","Error" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_descifrarPolybiosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ta_cifrarPolybios.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btn_limpiarDesPolyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarDesPolyActionPerformed
        // TODO add your handling code here:
         ta_descifrarPolybios.setText("");
    }//GEN-LAST:event_btn_limpiarDesPolyActionPerformed

    private void btn_cifrarTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarTriActionPerformed
        // TODO add your handling code here:
        String texto  = ta_cifrarTrithemius.getText().trim();
        
        if(soloLetras(texto) && !texto.isEmpty()){
            String cifrado = Trithemius.cifrar(texto, CBKeyCifrar.getSelectedIndex());
            ta_descrifrarTritemius.setText(cifrado);
        }else{
             JOptionPane.showMessageDialog(null, "Al parecer el campo de texto contine caracteres no validos o esta vacio." +
                        "\n Revise su texto y evite los saltos de linea.","Error" , JOptionPane.WARNING_MESSAGE);
        }
                   
    }//GEN-LAST:event_btn_cifrarTriActionPerformed

    private void btn_descifrarTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarTriActionPerformed
        // TODO add your handling code here:
         String texto  = ta_descrifrarTritemius.getText().trim();
        
        if(soloLetras(texto) && !texto.isEmpty()){
            Trithemius.descifrar(texto, CBKeydescifrar.getSelectedIndex());        
        }else{
             JOptionPane.showMessageDialog(null, "Al parecer el campo de texto contine caracteres no validos o esta vacio." +
                        "\n Revise su texto y evite los saltos de linea.","Error" , JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_descifrarTriActionPerformed

    private void btn_limpiarCifrarTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCifrarTriActionPerformed
        // TODO add your handling code here:
        ta_cifrarTrithemius.setText(" ");
    }//GEN-LAST:event_btn_limpiarCifrarTriActionPerformed

    private void btn_limpiarDesTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarDesTriActionPerformed
        // TODO add your handling code here:
          ta_descrifrarTritemius.setText(" ");
    }//GEN-LAST:event_btn_limpiarDesTriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });
    }
    
    
    
     //Método soloLetras, verifica que solo contenga letras
    public static boolean soloLetras(String cadena){
        for (int x = 0; x < cadena.trim().length(); x++) {
            char c = cadena.charAt(x);
            // Si no está entre a y z, ni entre A y Z, ni es un espacio
            if (!((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == ' ' || c == 'ñ')) {
                return false;}}
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Botones;
    private javax.swing.JComboBox<String> CBKeyCifrar;
    private javax.swing.JComboBox<String> CBKeydescifrar;
    private javax.swing.JComboBox<String> NDesencriptar;
    private javax.swing.JComboBox<String> NEncriptar;
    private javax.swing.JTabbedPane Paneles;
    private javax.swing.JButton btn_Cesar;
    private javax.swing.JButton btn_Info;
    private javax.swing.JButton btn_Polybios;
    private javax.swing.JButton btn_Trithemius;
    private javax.swing.JButton btn_cifrarCesar;
    private javax.swing.JButton btn_cifrarPolybios;
    private javax.swing.JButton btn_cifrarTri;
    private javax.swing.JButton btn_descifrarCesar;
    private javax.swing.JButton btn_descifrarPolybios;
    private javax.swing.JButton btn_descifrarTri;
    private javax.swing.JButton btn_limpiarCesarD;
    private javax.swing.JButton btn_limpiarCesarE;
    private javax.swing.JButton btn_limpiarCifrarTri;
    private javax.swing.JButton btn_limpiarDesPoly;
    private javax.swing.JButton btn_limpiarDesTri;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextPane ta_cifrarCesar;
    private javax.swing.JTextArea ta_cifrarPolybios;
    private javax.swing.JTextArea ta_cifrarTrithemius;
    private javax.swing.JTextArea ta_descifrarPolybios;
    private javax.swing.JTextArea ta_descrifrarCesar;
    private javax.swing.JTextArea ta_descrifrarTritemius;
    // End of variables declaration//GEN-END:variables
}
