/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package transposicion;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JOptionPane;

/**
 *
 * @author marti
 */
public class Desing extends javax.swing.JFrame {

    /**
     * Creates new form Desing
     */
    public Desing() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        BTN_FILAS = new javax.swing.JButton();
        BTN_COLUMNAS = new javax.swing.JButton();
        BTN_Vayas = new javax.swing.JButton();
        BTN_ABOUT = new javax.swing.JButton();
        Paneles = new javax.swing.JTabbedPane();
        Panel_Filas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_filasDescifar = new javax.swing.JComboBox<>();
        cifrar_fila = new javax.swing.JButton();
        btn_limpiarC = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area_cifrar = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_area_descrifrar = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_filasCifrar = new javax.swing.JComboBox<>();
        btn_descrifrar = new javax.swing.JButton();
        btn_limpiarTAD = new javax.swing.JButton();
        Panel_Columnas = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_AreacolumnaC = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        text_areaDC = new javax.swing.JTextArea();
        text_claveE = new javax.swing.JTextField();
        btn_cifradoColumna = new javax.swing.JButton();
        text_claveD = new javax.swing.JTextField();
        btn_descifrarC = new javax.swing.JButton();
        btn_limpiarTextADC = new javax.swing.JButton();
        btn_limpiarTextACD = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Panel_Vayas = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        text_areaCV = new javax.swing.JTextArea();
        cb_columnasC = new javax.swing.JComboBox<>();
        btn_cifrarVayas = new javax.swing.JButton();
        btn_limpiarCV = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        text_areaDV = new javax.swing.JTextArea();
        btn_limpiarDV = new javax.swing.JButton();
        btn_descifrarVayas = new javax.swing.JButton();
        cb_columnasD = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Panel_Infor = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programa de Transposición");
        setBackground(new java.awt.Color(0, 204, 153));
        setFocusCycleRoot(false);
        setForeground(new java.awt.Color(255, 204, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(660, 310));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        BTN_FILAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transposicion/Images/fila.png"))); // NOI18N
        BTN_FILAS.setContentAreaFilled(false);
        BTN_FILAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_FILASActionPerformed(evt);
            }
        });

        BTN_COLUMNAS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transposicion/Images/columna.png"))); // NOI18N
        BTN_COLUMNAS.setContentAreaFilled(false);
        BTN_COLUMNAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_COLUMNASActionPerformed(evt);
            }
        });

        BTN_Vayas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transposicion/Images/lineas-de-barra.png"))); // NOI18N
        BTN_Vayas.setContentAreaFilled(false);
        BTN_Vayas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_VayasActionPerformed(evt);
            }
        });

        BTN_ABOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transposicion/Images/info.png"))); // NOI18N
        BTN_ABOUT.setContentAreaFilled(false);
        BTN_ABOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ABOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_Vayas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_COLUMNAS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BTN_FILAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTN_ABOUT)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(2, 2, 2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BTN_FILAS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_COLUMNAS)
                .addGap(53, 53, 53)
                .addComponent(BTN_Vayas)
                .addGap(59, 59, 59)
                .addComponent(BTN_ABOUT)
                .addGap(41, 41, 41))
        );

        Paneles.setBackground(new java.awt.Color(0, 0, 51));
        Paneles.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        Paneles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Paneles.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        Paneles.setEnabled(false);
        Paneles.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Paneles.setMaximumSize(null);

        Panel_Filas.setBackground(new java.awt.Color(0, 0, 0));
        Panel_Filas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Transposición por FILAS");

        cb_filasDescifar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cifrar_fila.setText("Cifrar");
        cifrar_fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cifrar_filaActionPerformed(evt);
            }
        });

        btn_limpiarC.setText("Limpiar");
        btn_limpiarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("K:");

        text_area_cifrar.setColumns(20);
        text_area_cifrar.setLineWrap(true);
        text_area_cifrar.setRows(5);
        text_area_cifrar.setToolTipText("");
        jScrollPane1.setViewportView(text_area_cifrar);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese el mensaje a cifrar:");

        text_area_descrifrar.setColumns(20);
        text_area_descrifrar.setLineWrap(true);
        text_area_descrifrar.setRows(5);
        jScrollPane2.setViewportView(text_area_descrifrar);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese el mensaje a descifrar:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("K:");

        cb_filasCifrar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btn_descrifrar.setText("Descifrar");
        btn_descrifrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descrifrarActionPerformed(evt);
            }
        });

        btn_limpiarTAD.setText("Limpiar");
        btn_limpiarTAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarTADActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_FilasLayout = new javax.swing.GroupLayout(Panel_Filas);
        Panel_Filas.setLayout(Panel_FilasLayout);
        Panel_FilasLayout.setHorizontalGroup(
            Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FilasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel3)
                    .addGroup(Panel_FilasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_filasCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cifrar_fila, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiarC)))
                .addGroup(Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_FilasLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4))
                    .addGroup(Panel_FilasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_FilasLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_filasDescifar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_descrifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_limpiarTAD, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_FilasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(202, 202, 202))
        );
        Panel_FilasLayout.setVerticalGroup(
            Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_FilasLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Panel_FilasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cifrar_fila)
                    .addComponent(btn_limpiarC)
                    .addComponent(cb_filasCifrar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(cb_filasDescifar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_descrifrar)
                    .addComponent(btn_limpiarTAD))
                .addGap(80, 80, 80))
        );

        Paneles.addTab("Filas", Panel_Filas);

        Panel_Columnas.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transpoción por Columnas");

        text_AreacolumnaC.setColumns(20);
        text_AreacolumnaC.setLineWrap(true);
        text_AreacolumnaC.setRows(5);
        jScrollPane3.setViewportView(text_AreacolumnaC);

        text_areaDC.setColumns(20);
        text_areaDC.setLineWrap(true);
        text_areaDC.setRows(5);
        jScrollPane4.setViewportView(text_areaDC);

        btn_cifradoColumna.setText("Cifrar");
        btn_cifradoColumna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifradoColumnaActionPerformed(evt);
            }
        });

        btn_descifrarC.setText("Descrifrar");
        btn_descifrarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarCActionPerformed(evt);
            }
        });

        btn_limpiarTextADC.setText("Limpiar");
        btn_limpiarTextADC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarTextADCActionPerformed(evt);
            }
        });

        btn_limpiarTextACD.setText("Limpiar");
        btn_limpiarTextACD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarTextACDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Clave:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clave:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Ingrese su texto a cifrar");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Ingrese su texto a cifrar");

        javax.swing.GroupLayout Panel_ColumnasLayout = new javax.swing.GroupLayout(Panel_Columnas);
        Panel_Columnas.setLayout(Panel_ColumnasLayout);
        Panel_ColumnasLayout.setHorizontalGroup(
            Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ColumnasLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ColumnasLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(text_claveE))
                    .addGroup(Panel_ColumnasLayout.createSequentialGroup()
                        .addComponent(btn_cifradoColumna, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_limpiarTextACD))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addGroup(Panel_ColumnasLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(Panel_ColumnasLayout.createSequentialGroup()
                            .addComponent(btn_descifrarC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_limpiarTextADC))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ColumnasLayout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(text_claveD, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ColumnasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(196, 196, 196))
        );
        Panel_ColumnasLayout.setVerticalGroup(
            Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ColumnasLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(text_claveE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(text_claveD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(Panel_ColumnasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cifradoColumna)
                    .addComponent(btn_descifrarC)
                    .addComponent(btn_limpiarTextADC)
                    .addComponent(btn_limpiarTextACD))
                .addGap(28, 28, 28))
        );

        Paneles.addTab("Columnas", Panel_Columnas);

        Panel_Vayas.setBackground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Trasposición por Vayas");

        text_areaCV.setColumns(20);
        text_areaCV.setLineWrap(true);
        text_areaCV.setRows(5);
        jScrollPane5.setViewportView(text_areaCV);

        cb_columnasC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btn_cifrarVayas.setText("Cifrar");
        btn_cifrarVayas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cifrarVayasActionPerformed(evt);
            }
        });

        btn_limpiarCV.setText("Limpiar");
        btn_limpiarCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarCVActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Key");

        text_areaDV.setColumns(20);
        text_areaDV.setLineWrap(true);
        text_areaDV.setRows(5);
        jScrollPane7.setViewportView(text_areaDV);

        btn_limpiarDV.setText("Limpiar");
        btn_limpiarDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarDVActionPerformed(evt);
            }
        });

        btn_descifrarVayas.setText("Descifrar");
        btn_descifrarVayas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_descifrarVayasActionPerformed(evt);
            }
        });

        cb_columnasD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Key");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Ingrese su texto a cifrar:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ingrese su texto a cifrar:");

        javax.swing.GroupLayout Panel_VayasLayout = new javax.swing.GroupLayout(Panel_Vayas);
        Panel_Vayas.setLayout(Panel_VayasLayout);
        Panel_VayasLayout.setHorizontalGroup(
            Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VayasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_VayasLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_columnasC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cifrarVayas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_limpiarCV))
                    .addComponent(jScrollPane5)
                    .addGroup(Panel_VayasLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(Panel_VayasLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cb_columnasD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_descifrarVayas)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_limpiarDV)))
                    .addComponent(jLabel15))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_VayasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(195, 195, 195))
        );
        Panel_VayasLayout.setVerticalGroup(
            Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_VayasLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Panel_VayasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cifrarVayas)
                    .addComponent(btn_limpiarCV)
                    .addComponent(cb_columnasC, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(cb_columnasD, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_descifrarVayas)
                    .addComponent(btn_limpiarDV))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        Paneles.addTab("Vayas", Panel_Vayas);

        Panel_Infor.setBackground(new java.awt.Color(0, 0, 0));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("PROGRAMA DE TRANSPOSICIÓN ");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transposicion/Images/matriz.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("- Transposición por Filas");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("- Transposición por Columnas");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("- Transposición por Vayas");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Creado por:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("M a r t i n   L ó p e z   R o b l e s ");

        javax.swing.GroupLayout Panel_InforLayout = new javax.swing.GroupLayout(Panel_Infor);
        Panel_Infor.setLayout(Panel_InforLayout);
        Panel_InforLayout.setHorizontalGroup(
            Panel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InforLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(150, 150, 150))
            .addGroup(Panel_InforLayout.createSequentialGroup()
                .addGroup(Panel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panel_InforLayout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(Panel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InforLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(1, 1, 1))))
                    .addGroup(Panel_InforLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel22))
                    .addGroup(Panel_InforLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(Panel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        Panel_InforLayout.setVerticalGroup(
            Panel_InforLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InforLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel17)
                .addGap(30, 30, 30)
                .addComponent(jLabel16)
                .addGap(29, 29, 29)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addGap(51, 51, 51))
        );

        Paneles.addTab("Información", Panel_Infor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Paneles, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
  
    
    ///----------------
    private void BTN_FILASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_FILASActionPerformed
        // TODO add your handling code here:
        Paneles.setSelectedIndex(0);
    }//GEN-LAST:event_BTN_FILASActionPerformed

    private void BTN_COLUMNASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_COLUMNASActionPerformed
        // TODO add your handling code here:
         Paneles.setSelectedIndex(1);
    }//GEN-LAST:event_BTN_COLUMNASActionPerformed

    private void BTN_VayasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_VayasActionPerformed
        // TODO add your handling code here:
         Paneles.setSelectedIndex(2);
    }//GEN-LAST:event_BTN_VayasActionPerformed

    private void BTN_ABOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ABOUTActionPerformed
        // TODO add your handling code here:
         Paneles.setSelectedIndex(3);
    }//GEN-LAST:event_BTN_ABOUTActionPerformed

    private void btn_cifrarVayasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifrarVayasActionPerformed
        // Cifrado por Vayas
        //Obteine las variables a usar
        String mensaje = text_areaCV.getText();
        int key = cb_columnasC.getSelectedIndex()+2;
        //Valida si el mensaje es mayor que la llave
        if (mensaje.length()>key){  
        //Se llama el metodo cifrar de la Clase Vayas.java
        String mensaje_cifrado = Vayas.cifrar(mensaje, key);       
        Dialog_mensaje dialog = new Dialog_mensaje();
        dialog.mostrar_Mensaje("Cifrado por vayas:", mensaje_cifrado);
        text_areaDV.setText(mensaje_cifrado); 
        }else{
             JOptionPane.showMessageDialog(Panel_Columnas, "Su texto debe ser mayor a su clave"); 
        }          
    }//GEN-LAST:event_btn_cifrarVayasActionPerformed

    private void btn_descifrarVayasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarVayasActionPerformed
        // Descifrado Vayas
        //Obtiene las variables papi
        String mensaje = text_areaDV.getText();
        int key = cb_columnasD.getSelectedIndex()+2;
        //Valida que el mesaje sea mayor que la llave
        if(mensaje.length()>key){
        //Se llama al metodo descrifar de la clase Vayas.java
        String mensaje_descifrado = Vayas.descifrar(mensaje, key);
        //Muestra un poderoso dialogo
        Dialog_mensaje dialog = new Dialog_mensaje();
        dialog.mostrar_Mensaje("Descifrado por vayas:", mensaje_descifrado);
          }else{
             JOptionPane.showMessageDialog(Panel_Columnas, "Su texto debe ser mayor a su clave"); 
        }   
        
    }//GEN-LAST:event_btn_descifrarVayasActionPerformed

    private void btn_limpiarCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCVActionPerformed
        // limpia
        text_areaCV.setText(null);
    }//GEN-LAST:event_btn_limpiarCVActionPerformed

    private void btn_limpiarDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarDVActionPerformed
        // limpia
        text_areaDV.setText(null);
    }//GEN-LAST:event_btn_limpiarDVActionPerformed

    private void btn_limpiarTextACDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarTextACDActionPerformed
        // limpia
        text_AreacolumnaC.setText(null);
        text_claveE.setText(null);
    }//GEN-LAST:event_btn_limpiarTextACDActionPerformed

    private void btn_limpiarTextADCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarTextADCActionPerformed
        // limpia
        text_areaDC.setText(null);
        text_claveD.setText(null);
    }//GEN-LAST:event_btn_limpiarTextADCActionPerformed

    private void btn_descifrarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descifrarCActionPerformed
        // Decifrado por Columnas
        //Instancia de la clase Columnas.java
        Columnas columnas = new Columnas();
        //Variables a usar uwu
        String mensaje = text_areaDC.getText().trim();
        String key     = text_claveD.getText().trim();
        //obtiene el tamaño de la fila
        int fila = mensaje.length()/ key.length();
        if(mensaje.length()%key.length()!=0)
        fila++;
        int columna = key.length();
        //se llaman a los metodos de la clase columnas
        columnas.crear_matriz_D(mensaje, key, fila, columna);
        columnas.crearKey(key, columna);
        char [] [] descifrado = columnas.descrifrar(fila, columna);
        String msg_descifrado =  columnas.resultD(fila, columna, descifrado);
        //Se meustra el dialogo con el mensaje descifrado
        Dialog_mensaje dialog = new Dialog_mensaje();
        dialog.mostrar_Mensaje("Descifrado por Columnas:", msg_descifrado);
    }//GEN-LAST:event_btn_descifrarCActionPerformed

    private void btn_cifradoColumnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cifradoColumnaActionPerformed
        // Cifrado por columnas
        //Instancia de la clase Columnas
        Columnas columnas = new Columnas();
        //Variables a usar
        String mensaje = text_AreacolumnaC.getText().trim();
        String key     = text_claveE.getText().trim();
        //valida si los campos estan vacios 
        if(!mensaje.isEmpty() && !key.isEmpty()){
            //Se prepara la matriz xd
            int fila = mensaje.length()/ key.length();
                if(mensaje.length()%key.length()!=0)
                fila++;
                int columna = key.length();
                //Metodos de la clase columnas
                columnas.crear_matriz_e( mensaje, key, fila, columna);
                columnas.crearKey(key, columna);
                char [] [] cifrado = columnas.cifrar(fila, columna);
                String msg_cifrado =  columnas.resultE(fila, columna, cifrado);
                //muestra el dialogo con el resultado
                Dialog_mensaje dialog = new Dialog_mensaje();
                dialog.mostrar_Mensaje("Cifrado por Columnas:", msg_cifrado);

        text_areaDC.setText(msg_cifrado); 
        text_claveD.setText(key);
        } else{
            JOptionPane.showMessageDialog(Panel_Columnas, "Es probable que un campo este vacio");   
        }
    }//GEN-LAST:event_btn_cifradoColumnaActionPerformed

    private void btn_descrifrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_descrifrarActionPerformed
        // Desifrado por Filas
        //Variables
        String mensaje = text_area_descrifrar.getText();
        int fila = cb_filasDescifar.getSelectedIndex()+2;
        //valida
        if(mensaje.length()>fila && !mensaje.isEmpty()){
        //Obtiene las columnas de la clase Filas.java
        int columnas = Filas.obtenerColumna(mensaje, fila);
        //Crea la matriz mediante la calse Filas.java
        char [][] matriz = Filas.Crear_Matriz(new StringBuilder(mensaje), fila, columnas, false);
        String mensaje_descifrado = Filas.descrifrar(matriz, fila, columnas);
        //Muestra el resultado mediante un dialogo
        Dialog_mensaje dialog = new Dialog_mensaje();
        dialog.mostrar_Mensaje("Mensaje Descifrado: ", mensaje_descifrado);
         }else{
              JOptionPane.showMessageDialog(Panel_Columnas, "El tamaño de su mensaje debe ser mayor a K");                            
         }
    }//GEN-LAST:event_btn_descrifrarActionPerformed

    private void btn_limpiarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarCActionPerformed
        // TODO add your handling code here:
        text_area_cifrar.setText(null);
    }//GEN-LAST:event_btn_limpiarCActionPerformed

    private void cifrar_filaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cifrar_filaActionPerformed
        // Desifrado por filas
        //Variables
        String mensaje = text_area_cifrar.getText();
        int fila = cb_filasCifrar.getSelectedIndex()+2;
          //valida
        if(mensaje.length()>fila && !mensaje.isEmpty()){
        // Obtiene el numero de las columnas UwU
        int columnas = Filas.obtenerColumna(mensaje, fila);
         //Crea la matriz mediante la calse Filas.java
        char [][] matriz = Filas.Crear_Matriz(new StringBuilder(mensaje), fila, columnas, true);
        String mensaje_cifrado = Filas.cifrar(matriz, fila, columnas);
        //Muestra el resultado mediante un dialogo
        Dialog_mensaje dialog = new Dialog_mensaje();
        dialog.mostrar_Mensaje("Mensaje Cifrado: ", mensaje_cifrado);
            
        text_area_descrifrar.setText(mensaje_cifrado);  
        } else
                {
                   JOptionPane.showMessageDialog(Panel_Columnas, "El tamaño de su mensaje debe ser mayor a K");             
                }      
    }//GEN-LAST:event_cifrar_filaActionPerformed

    private void btn_limpiarTADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarTADActionPerformed
        // TODO add your handling code here:
        text_area_descrifrar.setText(null);
    }//GEN-LAST:event_btn_limpiarTADActionPerformed

    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ABOUT;
    private javax.swing.JButton BTN_COLUMNAS;
    private javax.swing.JButton BTN_FILAS;
    private javax.swing.JButton BTN_Vayas;
    private javax.swing.JPanel Panel_Columnas;
    private javax.swing.JPanel Panel_Filas;
    private javax.swing.JPanel Panel_Infor;
    private javax.swing.JPanel Panel_Vayas;
    private javax.swing.JTabbedPane Paneles;
    private javax.swing.JButton btn_cifradoColumna;
    private javax.swing.JButton btn_cifrarVayas;
    private javax.swing.JButton btn_descifrarC;
    private javax.swing.JButton btn_descifrarVayas;
    private javax.swing.JButton btn_descrifrar;
    private javax.swing.JButton btn_limpiarC;
    private javax.swing.JButton btn_limpiarCV;
    private javax.swing.JButton btn_limpiarDV;
    private javax.swing.JButton btn_limpiarTAD;
    private javax.swing.JButton btn_limpiarTextACD;
    private javax.swing.JButton btn_limpiarTextADC;
    private javax.swing.JComboBox<String> cb_columnasC;
    private javax.swing.JComboBox<String> cb_columnasD;
    private javax.swing.JComboBox<String> cb_filasCifrar;
    private javax.swing.JComboBox<String> cb_filasDescifar;
    private javax.swing.JButton cifrar_fila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea text_AreacolumnaC;
    private javax.swing.JTextArea text_areaCV;
    private javax.swing.JTextArea text_areaDC;
    private javax.swing.JTextArea text_areaDV;
    private javax.swing.JTextArea text_area_cifrar;
    private javax.swing.JTextArea text_area_descrifrar;
    private javax.swing.JTextField text_claveD;
    private javax.swing.JTextField text_claveE;
    // End of variables declaration//GEN-END:variables
}
