/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postulados;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author marti
 */
public class Design extends javax.swing.JFrame {

    DefaultTableModel model_tabla = new DefaultTableModel();
    
    public Design() {
        initComponents();
         model_tabla = (DefaultTableModel) tabla_rachas.getModel();
         setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        et_texto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_verificar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_tbits_G1 = new javax.swing.JLabel();
        txt_ceros = new javax.swing.JLabel();
        txt_unos = new javax.swing.JLabel();
        txt_pG1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_tbitsG2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_rachas = new javax.swing.JTable();
        text_pG2 = new javax.swing.JLabel();
        txt_binario = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        text_area_bin = new javax.swing.JTextArea();
        btn_limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Postulados de Golomb Martin López Robles");
        setBackground(new java.awt.Color(102, 102, 102));
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(600, 420));
        setMinimumSize(new java.awt.Dimension(600, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("POSTULADOS DE GOLOMB");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(219, 11, 185, 31);

        et_texto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                et_textoKeyTyped(evt);
            }
        });
        getContentPane().add(et_texto);
        et_texto.setBounds(30, 70, 175, 30);

        jLabel2.setText("Ingrese su texto:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 160, 14);

        btn_verificar.setText("Verificar");
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_verificar);
        btn_verificar.setBounds(220, 70, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Postulado G1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 166, 74, 14);

        txt_tbits_G1.setText("Total de bits: ...");
        getContentPane().add(txt_tbits_G1);
        txt_tbits_G1.setBounds(26, 198, 175, 14);

        txt_ceros.setText("Numero total de 0: ...");
        getContentPane().add(txt_ceros);
        txt_ceros.setBounds(26, 238, 175, 14);

        txt_unos.setText("Numero total de 1: ...");
        getContentPane().add(txt_unos);
        txt_unos.setBounds(26, 282, 175, 14);

        txt_pG1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_pG1.setForeground(new java.awt.Color(0, 102, 102));
        txt_pG1.setText("Cumple el postulado G1: ...");
        getContentPane().add(txt_pG1);
        txt_pG1.setBounds(30, 350, 175, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Postulado G2");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 160, 74, 14);

        txt_tbitsG2.setText("Total de bits: ...");
        getContentPane().add(txt_tbitsG2);
        txt_tbitsG2.setBounds(267, 198, 218, 14);

        tabla_rachas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rachas"
            }
        ));
        tabla_rachas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla_rachas.setAutoscrolls(false);
        jScrollPane2.setViewportView(tabla_rachas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(270, 220, 292, 112);

        text_pG2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        text_pG2.setForeground(new java.awt.Color(0, 102, 102));
        text_pG2.setText("Cumple el postulado G2: ...");
        getContentPane().add(text_pG2);
        text_pG2.setBounds(270, 350, 218, 20);

        txt_binario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txt_binario.setText("Binario: ");
        getContentPane().add(txt_binario);
        txt_binario.setBounds(30, 130, 45, 14);

        text_area_bin.setColumns(20);
        text_area_bin.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        text_area_bin.setLineWrap(true);
        text_area_bin.setRows(5);
        text_area_bin.setEnabled(false);
        jScrollPane3.setViewportView(text_area_bin);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(81, 115, 484, 38);

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar);
        btn_limpiar.setBounds(330, 70, 77, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 600, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        // TODO add your handling code here:
           model_tabla.setRowCount(0);
           String text = et_texto.getText().trim();        
           if(text.length()>=8 && text.length()<=16){
               
                Postulados postulados = new Postulados();
               
                String txt_binario = Postulados.txt_binario(text.trim());
                txt_tbits_G1.setText("Total de bits: "+txt_binario.length());
                txt_tbitsG2.setText("Total de bits: "+txt_binario.length());
                text_area_bin.setText("");
                text_area_bin.setText(txt_binario);
                postulados.postulado_uno(txt_binario, txt_ceros, txt_unos, txt_pG1);
                postulados.postulado_dos(txt_binario,model_tabla, text_pG2);   
                
                
           }else{
               JOptionPane.showMessageDialog(null,"El numero de caracteres debe ser\n mayor a 7 y menor que 17");
           }
              
        
        
    }//GEN-LAST:event_btn_verificarActionPerformed

    private void et_textoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_et_textoKeyTyped
        // TODO add your handling code here:
        et_texto.setText(et_texto.getText().trim());
    }//GEN-LAST:event_et_textoKeyTyped

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // TODO add your handling code here:
        et_texto.setText(null);
        model_tabla.setRowCount(0);
       
          
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Design.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Design().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JTextField et_texto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla_rachas;
    private javax.swing.JTextArea text_area_bin;
    private javax.swing.JLabel text_pG2;
    private javax.swing.JLabel txt_binario;
    private javax.swing.JLabel txt_ceros;
    private javax.swing.JLabel txt_pG1;
    private javax.swing.JLabel txt_tbitsG2;
    private javax.swing.JLabel txt_tbits_G1;
    private javax.swing.JLabel txt_unos;
    // End of variables declaration//GEN-END:variables
}
